apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "guess-game.labels" . | nindent 4 }}
    {{- include "guess-game.backend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "guess-game.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
