apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guess-game.fullname" . }}-backend
  labels:
    {{- include "guess-game.labels" . | nindent 4 }}
    {{- include "guess-game.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "guess-game.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guess-game.backend.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres {{ .Values.postgres.port }}; do
                echo "Aguardando PostgreSQL..."; sleep 3;
              done
              echo "PostgreSQL pronto!"
      containers:
        - name: backend
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "run.py"
            - name: FLASK_DB_TYPE
              value: "postgres"
            - name: FLASK_DB_HOST
              value: "postgres"
            - name: FLASK_DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: FLASK_DB_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: FLASK_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "guess-game.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: FLASK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "guess-game.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
