apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "guess-game.labels" . | nindent 4 }}
    {{- include "guess-game.postgres.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "guess-game.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
